name: Test User Applications

on: [ push, pull_request ]

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  coding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix-build tests/coding.nix
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix-build tests/core.nix
  fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix-build tests/fonts.nix
  terminal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix-build tests/terminal.nix
  theming:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix-build tests/theming.nix
  vis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix-build tests/vis.nix
